services:
  kapitan_db :
    image : kapitan_db
    environment : 
      - MYSQL_ROOT_PASSWORD=tobechanged
    restart: always
  admin_server :
    image : dev_kapitan_admin_server 
    ports : 
      - 7474:5454
    volumes :
      - ./server_keys/:/server_ssl/
      - ./user_files/:/user_files/
      - ./AdminServer/src/:/webApp/
      - ./generic_client_bundle/client_dev.py:/generic_client_bundle/client.py
    restart: always
    depends_on :
      - kapitan_db
    environment :
      - FLASK_SECRET_PASSWORD=tobechanged
      - DB_USER=root
      - DB_PASSWORD=tobechanged
      - DB_NAME=kapitan_db 
      - DB_HOSTNAME=kapitan_db
      - API_SERVER_IP=localhost
      - TOKEN_SIGNING_SECRET=a_secret_string_that_is_the_same_for_both_server
  api_server:
    image : dev_kapitan_api_server
    ports : 
      - 9494:5454
    volumes : 
      - ./server_keys/:/server_ssl/
      - ./user_files/:/user_files/
      - ./ApiServer/src/:/webApp/
    restart: always
    depends_on :
      - kapitan_db
    environment :
      - FLASK_SECRET_PASSWORD=tobechanged
      - DB_USER=root
      - DB_PASSWORD=tobechanged
      - DB_NAME=kapitan_db 
      - DB_HOSTNAME=kapitan_db
      - TOKEN_SIGNING_SECRET=a_secret_string_that_is_the_same_for_both_server